CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230204162444_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230204162444_InitialCreate', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230213032729_CreateEdOrgRole') THEN
    CREATE TABLE "EducationOrganizations" (
        "EducationOrganizationId" uuid NOT NULL,
        "ParentOrganizationId" uuid,
        "Name" text NOT NULL,
        "Number" text,
        "EducationOrganizationType" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_EducationOrganizations" PRIMARY KEY ("EducationOrganizationId"),
        CONSTRAINT "FK_EducationOrganizations_EducationOrganizations_ParentOrganiz~" FOREIGN KEY ("ParentOrganizationId") REFERENCES "EducationOrganizations" ("EducationOrganizationId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230213032729_CreateEdOrgRole') THEN
    CREATE TABLE "Users" (
        "UserId" uuid NOT NULL,
        "IsSuperAdmin" boolean NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_Users_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230213032729_CreateEdOrgRole') THEN
    CREATE TABLE "UserRoles" (
        "UserRoleId" uuid NOT NULL,
        "EducationOrganizationId" uuid,
        "UserId" uuid,
        "Role" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserRoleId"),
        CONSTRAINT "FK_UserRoles_EducationOrganizations_EducationOrganizationId" FOREIGN KEY ("EducationOrganizationId") REFERENCES "EducationOrganizations" ("EducationOrganizationId"),
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230213032729_CreateEdOrgRole') THEN
    CREATE INDEX "IX_EducationOrganizations_ParentOrganizationId" ON "EducationOrganizations" ("ParentOrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230213032729_CreateEdOrgRole') THEN
    CREATE INDEX "IX_UserRoles_EducationOrganizationId" ON "UserRoles" ("EducationOrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230213032729_CreateEdOrgRole') THEN
    CREATE INDEX "IX_UserRoles_UserId" ON "UserRoles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230213032729_CreateEdOrgRole') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230213032729_CreateEdOrgRole', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230524041703_UniqueKeyOnUserRoles') THEN
    DROP INDEX "IX_UserRoles_EducationOrganizationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230524041703_UniqueKeyOnUserRoles') THEN
    CREATE UNIQUE INDEX "IX_UserRoles_EducationOrganizationId_UserId" ON "UserRoles" ("EducationOrganizationId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230524041703_UniqueKeyOnUserRoles') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230524041703_UniqueKeyOnUserRoles', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230528024804_AllOrganizationPermission') THEN
    ALTER TABLE "Users" ADD "AllEducationOrganizations" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230528024804_AllOrganizationPermission') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230528024804_AllOrganizationPermission', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    CREATE TABLE "EducationOrganizationConnectorSettings" (
        "EducationOrganizationConnectorSettingsId" uuid NOT NULL,
        "EducationOrganizationId" uuid,
        "Connector" text NOT NULL,
        "Settings" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_EducationOrganizationConnectorSettings" PRIMARY KEY ("EducationOrganizationConnectorSettingsId"),
        CONSTRAINT "FK_EducationOrganizationConnectorSettings_EducationOrganizatio~" FOREIGN KEY ("EducationOrganizationId") REFERENCES "EducationOrganizations" ("EducationOrganizationId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    CREATE TABLE "Requests" (
        "RequestId" uuid NOT NULL,
        "EducationOrganizationId" uuid,
        "Student" jsonb,
        "RequestManifest" jsonb,
        "RequestProcessUserId" uuid,
        "InitialRequestSentDate" timestamp with time zone,
        "ResponseManifest" jsonb,
        "ResponseProcessUserId" uuid,
        "RequestStatus" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_Requests" PRIMARY KEY ("RequestId"),
        CONSTRAINT "FK_Requests_EducationOrganizations_EducationOrganizationId" FOREIGN KEY ("EducationOrganizationId") REFERENCES "EducationOrganizations" ("EducationOrganizationId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    CREATE TABLE "Messages" (
        "MessageId" uuid NOT NULL,
        "RequestId" uuid NOT NULL,
        "RequestResponse" integer NOT NULL,
        "MessageTimestamp" timestamp with time zone NOT NULL,
        "MessageContents" jsonb,
        "TransmissionDetails" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId"),
        CONSTRAINT "FK_Messages_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("RequestId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    CREATE TABLE "PayloadContents" (
        "PayloadContentId" uuid NOT NULL,
        "MessageId" uuid NOT NULL,
        "ContentType" text,
        "BlobContent" bytea,
        "JsonContent" jsonb,
        "XmlContent" xml,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_PayloadContents" PRIMARY KEY ("PayloadContentId"),
        CONSTRAINT "FK_PayloadContents_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("MessageId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    CREATE UNIQUE INDEX "IX_EducationOrganizationConnectorSettings_EducationOrganizatio~" ON "EducationOrganizationConnectorSettings" ("EducationOrganizationId", "Connector");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    CREATE INDEX "IX_Messages_RequestId" ON "Messages" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    CREATE INDEX "IX_PayloadContents_MessageId" ON "PayloadContents" ("MessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    CREATE INDEX "IX_Requests_EducationOrganizationId" ON "Requests" ("EducationOrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001163815_ChangeEdOrgConnectorSettingsWithRequests') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231001163815_ChangeEdOrgConnectorSettingsWithRequests', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001203825_EdOrgPayloadSettings') THEN
    CREATE TABLE "EducationOrganizationPayloadSettings" (
        "EducationOrganizationPayloadSettingsId" uuid NOT NULL,
        "EducationOrganizationId" uuid,
        "PayloadDirection" integer,
        "Payload" text NOT NULL,
        "Settings" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_EducationOrganizationPayloadSettings" PRIMARY KEY ("EducationOrganizationPayloadSettingsId"),
        CONSTRAINT "FK_EducationOrganizationPayloadSettings_EducationOrganizations~" FOREIGN KEY ("EducationOrganizationId") REFERENCES "EducationOrganizations" ("EducationOrganizationId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001203825_EdOrgPayloadSettings') THEN
    CREATE UNIQUE INDEX "IX_EducationOrganizationPayloadSettings_EducationOrganizationI~" ON "EducationOrganizationPayloadSettings" ("EducationOrganizationId", "Payload");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231001203825_EdOrgPayloadSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231001203825_EdOrgPayloadSettings', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231105004550_EdOrgAddress') THEN
    ALTER TABLE "Requests" ALTER COLUMN "InitialRequestSentDate" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231105004550_EdOrgAddress') THEN
    ALTER TABLE "Messages" ALTER COLUMN "MessageTimestamp" TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231105004550_EdOrgAddress') THEN
    ALTER TABLE "EducationOrganizations" ADD "City" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231105004550_EdOrgAddress') THEN
    ALTER TABLE "EducationOrganizations" ADD "PostalCode" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231105004550_EdOrgAddress') THEN
    ALTER TABLE "EducationOrganizations" ADD "StateAbbreviation" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231105004550_EdOrgAddress') THEN
    ALTER TABLE "EducationOrganizations" ADD "StreetNumberName" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231105004550_EdOrgAddress') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231105004550_EdOrgAddress', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217031621_EdOrgPayloadSettingsUniqueIndex') THEN
    DROP INDEX "IX_EducationOrganizationPayloadSettings_EducationOrganizationI~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217031621_EdOrgPayloadSettingsUniqueIndex') THEN
    CREATE UNIQUE INDEX "IX_EducationOrganizationPayloadSettings_EducationOrganizationI~" ON "EducationOrganizationPayloadSettings" ("EducationOrganizationId", "Payload", "PayloadDirection");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217031621_EdOrgPayloadSettingsUniqueIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231217031621_EdOrgPayloadSettingsUniqueIndex', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217185805_AddRequestToPayloadContent') THEN
    ALTER TABLE "PayloadContents" DROP CONSTRAINT "FK_PayloadContents_Messages_MessageId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217185805_AddRequestToPayloadContent') THEN
    ALTER TABLE "PayloadContents" ALTER COLUMN "MessageId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217185805_AddRequestToPayloadContent') THEN
    ALTER TABLE "PayloadContents" ADD "RequestId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217185805_AddRequestToPayloadContent') THEN
    CREATE INDEX "IX_PayloadContents_RequestId" ON "PayloadContents" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217185805_AddRequestToPayloadContent') THEN
    ALTER TABLE "PayloadContents" ADD CONSTRAINT "FK_PayloadContents_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("MessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217185805_AddRequestToPayloadContent') THEN
    ALTER TABLE "PayloadContents" ADD CONSTRAINT "FK_PayloadContents_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("RequestId") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231217185805_AddRequestToPayloadContent') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231217185805_AddRequestToPayloadContent', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231230172936_DirectionColumnsforPayloadSettings') THEN
    DROP INDEX "IX_EducationOrganizationPayloadSettings_EducationOrganizationI~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231230172936_DirectionColumnsforPayloadSettings') THEN
    ALTER TABLE "EducationOrganizationPayloadSettings" DROP COLUMN "PayloadDirection";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231230172936_DirectionColumnsforPayloadSettings') THEN
    ALTER TABLE "EducationOrganizationPayloadSettings" RENAME COLUMN "Settings" TO "OutgoingPayloadSettings";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231230172936_DirectionColumnsforPayloadSettings') THEN
    ALTER TABLE "EducationOrganizationPayloadSettings" ADD "IncomingPayloadSettings" jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231230172936_DirectionColumnsforPayloadSettings') THEN
    CREATE UNIQUE INDEX "IX_EducationOrganizationPayloadSettings_EducationOrganizationI~" ON "EducationOrganizationPayloadSettings" ("EducationOrganizationId", "Payload");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231230172936_DirectionColumnsforPayloadSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231230172936_DirectionColumnsforPayloadSettings', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240113184827_AddFileNameToRequestContent') THEN
    ALTER TABLE "PayloadContents" ADD "FileName" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240113184827_AddFileNameToRequestContent') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240113184827_AddFileNameToRequestContent', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240115175624_WorkerStateFields') THEN
    ALTER TABLE "Requests" ADD "ProcessState" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240115175624_WorkerStateFields') THEN
    ALTER TABLE "Requests" ADD "WorkerInstance" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240115175624_WorkerStateFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240115175624_WorkerStateFields', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240115224130_MessageTimestampNull') THEN
    ALTER TABLE "Messages" ALTER COLUMN "MessageTimestamp" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240115224130_MessageTimestampNull') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240115224130_MessageTimestampNull', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240121001214_DomainForEdOrg') THEN
    ALTER TABLE "EducationOrganizations" ADD "Domain" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240121001214_DomainForEdOrg') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240121001214_DomainForEdOrg', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240121233557_EdOrgUniqueIndexForDomain') THEN
    CREATE UNIQUE INDEX "IX_EducationOrganizations_Domain" ON "EducationOrganizations" ("Domain");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240121233557_EdOrgUniqueIndexForDomain') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240121233557_EdOrgUniqueIndexForDomain', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240127173708_EdOrgAddressContacts') THEN
    ALTER TABLE "EducationOrganizations" DROP COLUMN "City";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240127173708_EdOrgAddressContacts') THEN
    ALTER TABLE "EducationOrganizations" DROP COLUMN "PostalCode";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240127173708_EdOrgAddressContacts') THEN
    ALTER TABLE "EducationOrganizations" DROP COLUMN "StateAbbreviation";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240127173708_EdOrgAddressContacts') THEN
    ALTER TABLE "EducationOrganizations" DROP COLUMN "StreetNumberName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240127173708_EdOrgAddressContacts') THEN
    ALTER TABLE "EducationOrganizations" ADD "Address" jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240127173708_EdOrgAddressContacts') THEN
    ALTER TABLE "EducationOrganizations" ADD "Contacts" jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240127173708_EdOrgAddressContacts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240127173708_EdOrgAddressContacts', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240128155241_EdOrgOnRequestsNotNull') THEN
    ALTER TABLE "Requests" DROP CONSTRAINT "FK_Requests_EducationOrganizations_EducationOrganizationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240128155241_EdOrgOnRequestsNotNull') THEN
    UPDATE "Requests" SET "EducationOrganizationId" = '00000000-0000-0000-0000-000000000000' WHERE "EducationOrganizationId" IS NULL;
    ALTER TABLE "Requests" ALTER COLUMN "EducationOrganizationId" SET NOT NULL;
    ALTER TABLE "Requests" ALTER COLUMN "EducationOrganizationId" SET DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240128155241_EdOrgOnRequestsNotNull') THEN
    ALTER TABLE "Requests" ADD CONSTRAINT "FK_Requests_EducationOrganizations_EducationOrganizationId" FOREIGN KEY ("EducationOrganizationId") REFERENCES "EducationOrganizations" ("EducationOrganizationId") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240128155241_EdOrgOnRequestsNotNull') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240128155241_EdOrgOnRequestsNotNull', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240128164341_AddIncomingOutgoingToRequest') THEN
    ALTER TABLE "Requests" ADD "IncomingOutgoing" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240128164341_AddIncomingOutgoingToRequest') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240128164341_AddIncomingOutgoingToRequest', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240204232437_PayloadToRequest') THEN
    ALTER TABLE "Requests" ADD "Payload" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240204232437_PayloadToRequest') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240204232437_PayloadToRequest', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240217183535_InitialMapping') THEN
    CREATE TABLE "Mappings" (
        "MappingId" uuid NOT NULL,
        "RequestId" uuid,
        "OriginalSchema" jsonb,
        "MappingType" text,
        "StudentAttributes" jsonb,
        "SourceMapping" jsonb,
        "DestinationMapping" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_Mappings" PRIMARY KEY ("MappingId"),
        CONSTRAINT "FK_Mappings_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("RequestId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240217183535_InitialMapping') THEN
    CREATE INDEX "IX_Mappings_RequestId" ON "Mappings" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240217183535_InitialMapping') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240217183535_InitialMapping', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240224213726_FixDateTimeFields') THEN
    ALTER TABLE "Requests" ALTER COLUMN "InitialRequestSentDate" TYPE timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240224213726_FixDateTimeFields') THEN
    ALTER TABLE "Messages" ALTER COLUMN "MessageTimestamp" TYPE timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240224213726_FixDateTimeFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240224213726_FixDateTimeFields', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240527154130_AddPayloadContentActions') THEN
    ALTER TABLE "PayloadContents" ADD "Action" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240527154130_AddPayloadContentActions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240527154130_AddPayloadContentActions', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240601182805_PayloadContentActionToJson') THEN
    ALTER TABLE "PayloadContents" DROP COLUMN "Action";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240601182805_PayloadContentActionToJson') THEN
    ALTER TABLE "PayloadContents" ADD "Actions" jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240601182805_PayloadContentActionToJson') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240601182805_PayloadContentActionToJson', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240623214538_AddWorkerJobs') THEN
    CREATE TABLE "Worker_Jobs" (
        "JobId" uuid NOT NULL,
        "QueueDateTime" timestamp with time zone NOT NULL,
        "StartDateTime" timestamp with time zone,
        "FinishDateTime" timestamp with time zone,
        "JobType" text,
        "JobParameters" jsonb,
        "ReferenceType" text,
        "ReferenceGuid" uuid,
        "JobStatus" integer NOT NULL,
        "WorkerInstance" text,
        "WorkerState" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_Worker_Jobs" PRIMARY KEY ("JobId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240623214538_AddWorkerJobs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240623214538_AddWorkerJobs', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240629201350_ChangeMappingToPayloadContent') THEN
    ALTER TABLE "Mappings" DROP CONSTRAINT "FK_Mappings_Requests_RequestId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240629201350_ChangeMappingToPayloadContent') THEN
    ALTER TABLE "Mappings" RENAME COLUMN "RequestId" TO "PayloadContentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240629201350_ChangeMappingToPayloadContent') THEN
    ALTER INDEX "IX_Mappings_RequestId" RENAME TO "IX_Mappings_PayloadContentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240629201350_ChangeMappingToPayloadContent') THEN
    ALTER TABLE "Mappings" ADD CONSTRAINT "FK_Mappings_PayloadContents_PayloadContentId" FOREIGN KEY ("PayloadContentId") REFERENCES "PayloadContents" ("PayloadContentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240629201350_ChangeMappingToPayloadContent') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240629201350_ChangeMappingToPayloadContent', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    ALTER TABLE "Mappings" DROP CONSTRAINT "FK_Mappings_PayloadContents_PayloadContentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    DROP INDEX "IX_Mappings_PayloadContentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    ALTER TABLE "PayloadContents" DROP COLUMN "Actions";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    ALTER TABLE "Mappings" RENAME COLUMN "SourceMapping" TO "JsonSourceMapping";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    ALTER TABLE "Mappings" RENAME COLUMN "PayloadContentId" TO "PayloadContentActionId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    ALTER TABLE "Mappings" RENAME COLUMN "DestinationMapping" TO "JsonDestinationMapping";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    ALTER TABLE "Mappings" ADD "Version" smallint NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    CREATE TABLE "PayloadContentActions" (
        "PayloadContentActionId" uuid NOT NULL,
        "PayloadContentId" uuid,
        "PayloadContentActionType" text,
        "ActiveMappingId" uuid,
        "Settings" jsonb,
        "Process" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_PayloadContentActions" PRIMARY KEY ("PayloadContentActionId"),
        CONSTRAINT "FK_PayloadContentActions_Mappings_ActiveMappingId" FOREIGN KEY ("ActiveMappingId") REFERENCES "Mappings" ("MappingId"),
        CONSTRAINT "FK_PayloadContentActions_PayloadContents_PayloadContentId" FOREIGN KEY ("PayloadContentId") REFERENCES "PayloadContents" ("PayloadContentId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    CREATE UNIQUE INDEX "IX_Mappings_PayloadContentActionId_Version" ON "Mappings" ("PayloadContentActionId", "Version");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    CREATE UNIQUE INDEX "IX_PayloadContentActions_ActiveMappingId" ON "PayloadContentActions" ("ActiveMappingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    CREATE UNIQUE INDEX "IX_PayloadContentActions_PayloadContentId_PayloadContentAction~" ON "PayloadContentActions" ("PayloadContentId", "PayloadContentActionType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    ALTER TABLE "Mappings" ADD CONSTRAINT "FK_Mappings_PayloadContentActions_PayloadContentActionId" FOREIGN KEY ("PayloadContentActionId") REFERENCES "PayloadContentActions" ("PayloadContentActionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722044402_AddActions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240722044402_AddActions', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240811060116_AddSeeds') THEN
    CREATE TABLE "__BrokerSeedsHistory" (
        "SeedId" text NOT NULL,
        "SeedName" text NOT NULL,
        CONSTRAINT "PK___BrokerSeedsHistory" PRIMARY KEY ("SeedId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240811060116_AddSeeds') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240811060116_AddSeeds', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240818170027_AddInitialMapping') THEN
    ALTER TABLE "Mappings" ADD "JsonInitialMapping" jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240818170027_AddInitialMapping') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240818170027_AddInitialMapping', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240819024037_AddPayloadContentActionStatus') THEN
    ALTER TABLE "PayloadContentActions" ADD "PayloadContentActionStatus" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240819024037_AddPayloadContentActionStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240819024037_AddPayloadContentActionStatus', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240819035956_AddProcessStateToPayloadContentAction') THEN
    ALTER TABLE "PayloadContentActions" ADD "ProcessState" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240819035956_AddProcessStateToPayloadContentAction') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240819035956_AddProcessStateToPayloadContentAction', '8.0.8');
    END IF;
END $EF$;
COMMIT;


